### ISSUE TITLE
Program eval can't handle medium sized results (200-500mb)

### ISSUE THREAD

**Issue by eatonphil** [multiprocessio/datastation#102]
![image](https://user-images.githubusercontent.com/3925912/144722086-374cab51-de1f-4d60-9068-63d9441ab4aa.png)

```
Error evaluating panel:
Error: [ERROR] 2021-12-04T19:23:16.794Z Cannot create a string longer than 0x1fffffe8 characters 
    at Buffer.toString (node:buffer:783:17)
    at evalProgram (C:\Users\philn\multiprocess\datastation\desktop\panel\program.ts:85:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.handler (C:\Users\philn\multiprocess\datastation\desktop\panel\eval.ts:181:17)
    at main (C:\Users\philn\multiprocess\datastation\desktop\runner.ts:100:24)

    at ChildProcess.<anonymous> (C:\Users\philn\multiprocess\datastation\desktop\panel\eval.ts:120:18)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

**Comment by eatonphil** [comment]
Node can't build strings longer than 512mb. https://stackoverflow.com/questions/68230031/cannot-create-a-string-longer-than-0x1fffffe8-characters-in-json-parse
