### ISSUE TITLE
HTTPS, TLS support corporate certificate issuer

### ISSUE THREAD

**Issue by setop** [multiprocessio/datastation#130]
I try to access a resource through HTTPS using a certificate signed by my compagny. This certificate authority (CA) is not known by datastation. I fails

```
Error evaluating panel:
Error: [ERROR] 2021-12-22T09:11:31.713Z request to https://internal.server/resource failed, reason: unable to get local issuer certificate 
    at ClientRequest.<anonymous> (...\datastation-win32-x64-0.4.0\resources\app.asar\node_modules\node-fetch\src\index.js:95:4)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

    at ChildProcess.<anonymous> (...\datastation-win32-x64-0.4.0\resources\app.asar\desktop\panel\eval.ts:120:28)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```
A solution could be to allow to bypass server certificate verification or better, to be able to add the CA in the tool.

**Comment by eatonphil** [comment]
Hey thanks for the report! Yes I plan to add support for custom CAs. I'll post back on this issue as that happens.

**Comment by eatonphil** [comment]
This has been merged and will be part of the next release.
